### ISSUE TITLE
Scenario maps in ComCat are using non-existent MapQuest basemap tiles

### ISSUE THREAD

**Issue by lisa-usgs** [usgs/shakemap-scenarios#25]
On scenario interactive maps, the Leaflet/Mapquest? layers "Street" or "Satellite" give errors when selected?
See: http://earthquake.usgs.gov/scenarios/eventpage/bssc2014829ab_m7p_se#general, for example. Seems to be the case for all the scenarios in comcat.

David

**Comment by emthompson-usgs** [comment]
This is really an issue related to the scenario comcat app. [Here](http://earthquake.usgs.gov/scenarios/eventpage/aklegacy1938kodiak_se#map) is a link to an example interactive map where the problem comes up, but this appears to occur across the board. We get error about "direct tile access" being discontinued. But this does not happen on the event pages for events in real comcat. 
![screen shot 2016-11-07 at 3 16 38 pm](https://cloud.githubusercontent.com/assets/15928870/20078370/80fb996e-a4fd-11e6-8c69-e329ae7bf58f.png)

**Comment by jmfee-usgs** [comment]
This would be better placed in the earthquake-eventpages project, it may only require a re-deploy of the latest version for scenarios.

**Comment by lisa-usgs** [comment]
OK, moving this yet again to the earthquake-eventpages project:
https://github.com/usgs/earthquake-eventpages/issues/665
